/* Parser.java */
/* Generated by: ParserGeneratorCC: Do not edit this line. Parser.java */
package parser;

import nodes.*;
import state.*;
import java.util.List;
import java.util.ArrayList;

public class Parser implements ParserConstants {

  final public ASTNode Start() throws ParseException {//	List<ASTNode> nodes = new ArrayList<>();
 ASTNode node;
    //   (node = Statment() ((<STAT_ENDS> | <EOF>) Statment())* (<EOF>)?
    //   {return node;}
    //   )?
        node = Statment();
{if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public ASTNode Statment() throws ParseException {ASTNode node;
    node = Expression();
    jj_consume_token(SEMICOLON);
{if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

// EXPERIMENTAL -==-----------------------------------
  final public ASTNode Expression() throws ParseException {ASTNode node;
    node = Equality();
{if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

//ASTNode Disjunction() :
//{
//    ASTNode node;
//}
//{
//    node = Conjunction() ((<NL>)* <DISJ> (<NL>)* Conjunction())*
//    { return node; }
//}
//
//ASTNode Conjunction() :
//{
//    ASTNode node;
//}
//{
//    node = Equality() ((<NL>)* <CONJ> (<NL>)* Equality())*
//    { return node; }
//}
  final public 
ASTNode Equality() throws ParseException {Token op;
    ASTNode node;
    node = Comparison();
    label_1:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case EQEQ:
      case EXCL_EQUALS:{
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case EQEQ:{
        op = jj_consume_token(EQEQ);
        break;
        }
      case EXCL_EQUALS:{
        op = jj_consume_token(EXCL_EQUALS);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Comparison();
    }
{if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public ASTNode Comparison() throws ParseException {Token op;
    ASTNode node;
    node = addSubExpression();
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case GREATER:
    case LESS:
    case GR_EQUALS:
    case LE_EQUALS:{
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case GREATER:{
        op = jj_consume_token(GREATER);
        break;
        }
      case LESS:{
        op = jj_consume_token(LESS);
        break;
        }
      case GR_EQUALS:{
        op = jj_consume_token(GR_EQUALS);
        break;
        }
      case LE_EQUALS:{
        op = jj_consume_token(LE_EQUALS);
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      addSubExpression();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
{if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public ASTNode addSubExpression() throws ParseException {Token op;
    ASTNode node, node2;
    node = multDivExpression();
    label_2:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case ADD:
      case SUB:{
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case ADD:{
        op = jj_consume_token(ADD);
        break;
        }
      case SUB:{
        op = jj_consume_token(SUB);
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      node2 = multDivExpression();
if (op.kind == ADD)
                             node = new ASTAddition(node,node2);
                       else  node = new ASTSubtraction(node,node2);
    }
{if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public ASTNode multDivExpression() throws ParseException {Token op;
    ASTNode node, node2;
    node = Unary();
    label_3:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case MULT:
      case DIV:{
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_3;
      }
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case MULT:{
        op = jj_consume_token(MULT);
        break;
        }
      case DIV:{
        op = jj_consume_token(DIV);
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      node2 = Unary();
if (op.kind == MULT)
                          node = new ASTMultiplication(node,node2);
                    else  node = new ASTDivision(node,node2);
    }
{if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public Token UnaryOperator() throws ParseException {Token t;
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case SUB:{
      t = jj_consume_token(SUB);
      break;
      }
    case EXCL:{
      t = jj_consume_token(EXCL);
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public ASTNode Unary() throws ParseException {Token op = null;
    ASTNode node;
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case SUB:
    case EXCL:{
      op = UnaryOperator();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    node = Fact();
if (op==null)
            {if ("" != null) return node;}
        switch(op.kind)
        {
            case SUB:
                node = new ASTNegate(node);
                break;
            case EXCL:
                node = new ASTNegate(node);
                break;
        }
        {if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public ASTNode Fact() throws ParseException {ASTNode node;
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case IDENTIFIER:{
      node = Identifier();
      break;
      }
    case LET:{
      node = Let();
      break;
      }
    case LPAR:{
      node = parenthesizedExpression();
      break;
      }
    case NUMBER:{
      node = Number();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public ASTNode Identifier() throws ParseException {Token id;
    ASTNode node;
    id = jj_consume_token(IDENTIFIER);
node = new ASTIdentifier(id.image);
        {if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public Declaration Declaration() throws ParseException {Token id;
    ASTNode exp;
    id = jj_consume_token(IDENTIFIER);
    jj_consume_token(EQUALS);
    exp = Expression();
{if ("" != null) return new Declaration(id.image,exp);}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public List<Declaration> DeclarationsList() throws ParseException {Declaration d;
    List<Declaration> list = new ArrayList<>();
    d = Declaration();
list.add(d);
    label_4:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case COMA:
      case IDENTIFIER:{
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_4;
      }
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case COMA:{
        jj_consume_token(COMA);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        ;
      }
      d = Declaration();
list.add(d);
    }
{if ("" != null) return list;}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public ASTNode Let() throws ParseException {List<Declaration> list;
    ASTNode body;
    jj_consume_token(LET);
    list = DeclarationsList();
    jj_consume_token(IN);
    body = Expression();
    jj_consume_token(END);
{if ("" != null) return new nodes.ASTLet(list,body);}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public ASTNode Number() throws ParseException {Token num;
    num = jj_consume_token(NUMBER);
{if ("" != null) return new ASTNumber(Integer.parseInt(num.image));}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public ASTNode parenthesizedExpression() throws ParseException {ASTNode node;
    jj_consume_token(LPAR);
    node = Expression();
    jj_consume_token(RPAR);
{if ("" != null) return node;}
    throw new IllegalStateException ("Missing return statement in function");
}

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[13];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x18000,0x18000,0x1e0000,0x1e0000,0x180,0x180,0x600,0x600,0x900,0x900,0x69000000,0x40000040,0x40,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}

  /**
   * Constructor with InputStream.
   * @param stream char stream
   */
  public Parser(final Provider stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
   for (int i = 0; i < 13; i++)
     jj_la1[i] = -1;
  }

  /**
   * Constructor with InputStream.
   * @param sDSL String representation to be parsed
   */
  public Parser(final String sDSL) {
	   this(new StringProvider(sDSL));
  }

  /**
   * Reinitialise.
   * @param sDSL String representation to be parsed
   */
  public void ReInit(final String sDSL) {
	  ReInit(new StringProvider(sDSL));
  }
  /**
   * Reinitialise
   * @param stream char stream
   */
  public void ReInit(final Provider stream) {
	if (jj_input_stream == null) {
	  jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	  jj_input_stream.reInit(stream, 1, 1);
  }
	if (token_source == null) {
 token_source = new ParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
   for (int i = 0; i < 13; i++)
     jj_la1[i] = -1;
  }

  /**
   * Constructor with generated Token Manager.
   * @param tm Token manager to use
   */
  public Parser(final ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /**
   * Reinitialise
   * @param tm Token manager to use
   */
  public void ReInit(final ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(final int kind) throws ParseException {
    final Token oldToken = token;
    if (token.next != null)
      token = token.next;
    else {
      token.next = token_source.getNextToken();
      token = token.next;
    }
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


  /**
   * @return the next Token.
   */
  public final Token getNextToken() {
   if (token.next != null)
     token = token.next;
   else
     token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

  /**
   * @param index index to be retrieved
   * @return the specific Token.
   */
  public final Token getToken(final int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next == null)
        t.next = token_source.getNextToken();
      t = t.next;
    }
    return t;
  }

  private int jj_ntk_f() {
    jj_nt = token.next;
    if (jj_nt == null) {
      token.next = token_source.getNextToken();
      jj_ntk = token.next.kind;
      return jj_ntk;
    }
    jj_ntk = jj_nt.kind;
    return jj_ntk;
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /**
   * Generate ParseException.
   * @return new Exception object. Never <code>null</code>
   */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[33];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 13; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 33; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage, token_source == null ? null : ParserTokenManager.lexStateNames[token_source.curLexState]);
  }

  /**
   * @return Always <code>false</code>.
   */
  public final boolean trace_enabled() {
    return false;
  }

  /** Enable tracing. */
  public final void enable_tracing() {}

  /** Disable tracing. */
  public final void disable_tracing() {}

}
